# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_app', '0002_auto_20191106_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='general_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
